name: video_processing_example
description: Demonstrates how to use the video_processing plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: 0.10.1+3
  path_provider: 1.5.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  video_processing:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
